services:
  web:
    image: nginx:1.25-alpine
    container_name: web_server
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: ./infra/backend
    container_name: backend_app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./infra/frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    # command: sh -c "tail -f /dev/null"
    command: npm run dev

  db:
    build: ./infra/mysql
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ./infra/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5