server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    
    # Laravelの公開ディレクトリ（public）を指定
    root /var/www/html/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block"; #XSS対策
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHPファイルへのアクセスが来たら、backendコンテナに流す設定
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # ★重要：docker-composeのサービス名「backend」の9000番ポートへ送る
        fastcgi_pass backend:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}